# Global Values
repoUrl: 'https://github.com/Quentral/eks-blueprints-add-ons.git'
targetRevision: HEAD
region: ''
account: ''
clusterName: ''

# Agones Values
agones:
  enable: false

# App Mesh Values
appMesh:
  enable: false

# Calico Values
calico:
  enable: false

# AWS CloudWatch Metrics Values
awsCloudWatchMetrics:
  enable: false
  serviceAccountName:

# AWS EFS CSI Driver Values
awsEfsCsiDriver:
  enable: false
  serviceAccountName:
  fileSystemId:

# AWS for Fluent Bit Values
awsForFluentBit:
  enable: false
  logGroupName:
  serviceAccountName:

# AWS Load Balancer Controller Values
awsLoadBalancerController:
  enable: false
  serviceAccountName:
  podDisruptionBudget:
    maxUnavailable: 1

# AWS Node Termination Handler Values
awsNodeTerminationHandler:
  enable: false
  serviceAccountName:

# AWS Otel Collector Values
awsOtelCollector:
  enable: false
  otlpEndpoint:
  resourceAttributes:

# Cert Manager Values
certManager:
  enable: false
  serviceAccountName:
  dnsZones:
  email:

# Cert Manager Values
certManagerIssuers:
  enable: false
  email:

# Cert Manager CSI Driver Values
certManagerCsiDriver:
  enable: false

# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:

# Datadog Operator
datadogOperator:
  enable: false

dbOperator:
  enable: false
  auroraPostgresAdminSecret: ""
  auroraPostgresHost: ""
  auroraPostgresPort: ""

# Strimzi Kafka Operator
strimziKafkaOperator:
  enabled: false

# External DNS Values
externalDns:
  enable: false
  serviceAccountName:
  zoneIdFilter:

# External DNS CLOUDFLARE
externalDnsCloudflare:
  enable: false
  serviceAccountName:
  domainFilters: []
  apiToken: ""

# Forecastle
forecastle:
  enable: false

# External Secrets Operator
externalSecrets:
  enable: false

# Gitlab Values
gitlab:
  enable: false
  region: ""
  awsAccountS3AccessKeyId: ""
  awsAccountS3SecretAccessKey: ""
  domain: ""
  auroraPostgresHost: ""

# Gatekeeper Values
gatekeeper:
  enable: false
  clusterName:

# Harbor Values
harbor:
  enable: false
  awsAccountS3AccessKeyId: ""
  awsAccountS3SecretAccessKey: ""
  domain: ""
  registryS3Bucket: ""
  auroraPostgresHost: ""
  auroraPostgresPort: "5432"
  region: ""

# Nginx Values
ingressNginx:
  enable: false

# Grafana default Values
grafana:
  enable: false
  serviceAccount:
    create: false

# Vault default Values
vault:
  enable: false

# Karpenter Values
karpenter:
  enable: false
  serviceAccountName:
  controllerClusterEndpoint:
  awsDefaultInstanceProfile:
  controllerClusterName:

# Keda Values
keda:
  enable: false
  serviceAccountName:

# Loki Values
loki:
  enable: false
  awsAccountS3AccessKeyId:
  awsAccountS3SecretAccessKey:
  region:

# Metrics Server Values
metricsServer:
  enable: false

# Ondat Values
ondat:
  enable: false
  etcdClusterCreate: false
  serviceAccountName:
  clusterSecretRefName:
  clusterAdminUsername:
  clusterAdminPassword:
  clusterKvBackendAddress:
  clusterKvBackendTLSSecretName:
  clusterKvBackendTLSSecretNamespace:
  clusterNodeSelectorTermKey:
  clusterNodeSelectorTermValue:
  etcdNodeSelectorTermKey:
  etcdNodeSelectorTermValue:
  etcdClusterReplicas:
  etcdClusterStorageclass:
  etcdClusterStorage:

# Prometheus Values
prometheus:
  enable: false
  serviceAccountName:
  roleArn:
  ampWorkspaceUrl:

# Metrics Server Values
sparkOperator:
  enable: false

# Teleport-cluster
teleportCluster:
  enable: false
  acmeEmail:
  domain: ""
  githubClientId: ""
  githubClientSecret: ""
  githubTeamsToRoles:
    - organization: Quentral
      team: admin
      roles:
        - access

# Teleport-kube-agent
teleportKubeAgent:
  enable: false

# Tetrate Istio Values
tetrateIstio:
  enable: false
  base:
  cni:
  istiod:
  global:

# Thanos Values
thanos:
  enable: false

# Traefik Values
traefik:
  enable: false

# VPA Values
vpa:
  enable: false

# Yunikorn Values
yunikorn:
  enable: false

# Argo Rollout Values
argoRollouts:
  enable: false

# Argo Rollout Values
argoWorkflows:
  enable: false

# Kube State Metrics Values
kubeStateMetrics:
  enable: false
  serviceAccountName:

# Kubernetes Dashboard Values
kubernetesDashboard:
  enable: false
  serviceAccountName:

# promtail Values
promtail:
  enable: false

# kubecost Values
kubecost:
  enable: false

# SMB CSI Driver Values
smbCsiDriver:
  enable: false

# Chaos Mesh Values
chaosMesh:
  enable: false

# Cilium Mesh Values
cilium:
  enable: false

# Reloader Values
reloader:
  enable: false

# Kube Prometheus Stack
kubePrometheusStack:
  enable: false

# Kyverno Values
kyverno:
  enable: false

policies:
  enable: false

reporter:
  enable: false

# NVIDIA Device Plugin Values
nvidiaDevicePlugin:
  enable: false

velero:
  enable: false

vcluster:
  enable: false
