apiVersion: resources.teleport.dev/v3
kind: TeleportGithubConnector
metadata:
  name: github
spec:
  client_id: {{ .Values.teleport_github_connector_client_id }}
  client_secret: {{ .Values.teleport_github_connector_client_secret }}
  display: Github
  redirect_url: https://{{ .Values.teleport_domain }}/v1/webapi/github/callback
  teams_to_roles:
    - organization: Quentral
      roles:
        - access
        - editor
      team: admin