gitlab_operator:
  global:
    edition: ce
    hosts:
      https: true
      domain: example.com # use a real domain here
    ingress:
      configureCertmanager: false
      provider: nginx
      class: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      enabled: true
      tls:
        enabled: true
        secretName: "global-gitlab-tls"
      path: /
      pathType: Prefix
    psql:
      host: ""
      password:
        useSecret: true
        secret: "gitlab-pg"
        key: "password"
      database: gitlab-gitlab
      username: gitlab
    minio:
      enabled: false
    grafana:
      enable: false
    registry:
      ingress:
        tls:
          secretName: "registry-gitlab-tls"
    runner:
      registrationToken:
        secret: "gitlab-gitlab-runner-secret"
    appConfig:
      object_store:
        enabled: true
        proxy_download: true
        storage_options: {}
        connection:
          secret: "gitlab-s3"
          key: "connection"
      lfs:
        enabled: true
        bucket: qke-git-lfs
      artifacts:
        enabled: true
        bucket: qke-gitlab-artifacts
      uploads:
        enabled: true
        bucket: qke-gitlab-uploads
      packages:
        enabled: true
        bucket: qke-gitlab-packages
      externalDiffs:
        enabled: false
        when:
        bucket: qke-gitlab-mr-diffs
      terraformState:
        enabled: false
        bucket: qke-gitlab-terraform-state
      ciSecureFiles:
        enabled: false
        bucket: qke-gitlab-ci-secure-files
      dependencyProxy:
        enabled: false
        bucket: qke-gitlab-dependency-proxy
      backups:
        bucket: qke-gitlab-backups
        tmpBucket: tmp
    kas:
      enabled: true
  nginx-ingress:
    enabled: false
  gitlab:
    webservice:
      ingress:
        tls:
          secretName: "gitlab-gitlab-tls"
  postgresql:
    install: false
  prometheus:
    install: false
  upgradeCheck:
    enabled: false
  registry:
    enabled: false
  gitlab-runner:
    install: false

# S3 bucket
s3_connect:
  region: ""
  aws_access_key_id: ""
  aws_secret_access_key: ""

# https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.8.1/CHART_VERSIONS
gitlab_version: "6.7.3"

# Gitlab runner
gitlab-runner:
  gitlabUrl: ""
  rbac:
    create: true
  runners:
    secret: "gitlab-gitlab-runner-secret"
    privileged: true