harbor:
  expose:
    type: ingress
    certSource: secret
    tls:
      secret:
        secretName: "harbor-tls"
  ingress:
    hosts:
      core: core.harbor.domain
    className: nginx
    annotations:
      cert-manager.io/clusterissuer: "letsencrypt-staging"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  externalURL: https://core.harbor.domain
  imageChartStorage:
    s3:
      # Set an existing secret for S3 accesskey and secretkey
      # keys in the secret should be AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for chartmuseum
      # keys in the secret should be REGISTRY_STORAGE_S3_ACCESSKEY and REGISTRY_STORAGE_S3_SECRETKEY for registry
      # existingSecret: ""
      accesskey: awsaccesskey
      secretkey: awssecretkey
      region: us-west-1
      bucket: bucketname
  notary:
    enabled: false
  database:
    type: external
    external:
      username: "registry"
      host:
      port:
      coreDatabase: "registry"
      existingSecret: "harbor-registry"