kube-prometheus-stack:
  # Create default rules for monitoring the cluster
  # Disable rules for unreachable components
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeScheduler: false

  # Fix admissionWebhooks for EKS
  # https://lyz-code.github.io/blue-book/devops/prometheus/prometheus_troubleshooting/
  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      failurePolicy: Ignore
      enabled: false
      timeoutSeconds: 30
      patch:
        enabled: true

  #  alertmanager:
  #    serviceMonitor:
  #      enableHttp2: false

  # Disable component scraping for the kube controller manager, etcd, and kube-scheduler
  # These components are not reachable on EKS
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false

  prometheus:
    prometheusSpec:
      # Prometheus StorageSpec for persistent data on AWS EBS
      # ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
      storageSpec:
       volumeClaimTemplate:
         spec:
           storageClassName: gp2
           accessModes: ["ReadWriteOnce"]
           resources:
             requests:
               storage: 20Gi