kube-prometheus-stack:
  # Create default rules for monitoring the cluster
  # Disable rules for unreachable components
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeScheduler: false

  # Fix admissionWebhooks for EKS
  # https://lyz-code.github.io/blue-book/devops/prometheus/prometheus_troubleshooting/
  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      failurePolicy: Ignore
      enabled: false
      timeoutSeconds: 30
      patch:
        enabled: true

  #  alertmanager:
  #    serviceMonitor:
  #      enableHttp2: false

  # Disable component scraping for the kube controller manager, etcd, and kube-scheduler
  # These components are not reachable on EKS
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false

  prometheus:
    prometheusSpec:
      # Prometheus StorageSpec for persistent data on AWS EBS
      # ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
      storageSpec:
       volumeClaimTemplate:
         spec:
           storageClassName: gp2
           accessModes: ["ReadWriteOnce"]
           resources:
             requests:
               storage: 20Gi

  grafana:
    forceDeployDatasources: true
    sidecar:
      datasources:
        isDefaultDatasource: false
    grafana.ini:
      auth.generic_oauth:
        enabled: true
        name: Keycloak
        allow_sign_up: true
        scopes: profile,email,groups,openid,offline_access,roles
        client_id: grafana
        client_secret: 0TAzmc3wbN2UfEC13gE77OOnYQrNG1Uf
        auth_url: https://keycloak.kube.quentrix.com/auth/realms/Quentral/protocol/openid-connect/auth
        token_url: https://keycloak.kube.quentrix.com/auth/realms/Quentral/protocol/openid-connect/token
        api_url: https://keycloak.kube.quentrix.com/auth/realms/Quentral/protocol/openid-connect/userinfo
        role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-user') && 'Editor' || 'Viewer'
      server:
        root_url: https://grafana.tele.quentrix.com
    additionalDataSources:
    - name: loki
      isDefault: true
      type: loki
      url: http://loki-read.loki:3100
      access: proxy