{{- if and (.Values.certManagerIssuers) (.Values.certManagerIssuers.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/cert-manager-issuers
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
      - name: clusterIssuers[0].spec.acme.email
        value: {{ .Values.certManagerIssuers.email }}
      - name: clusterIssuers[1].spec.acme.email
        value: {{ .Values.certManagerIssuers.email }}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager-issuers
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
