{{- if and (.Values.externalDnsCloudflare) (.Values.externalDnsCloudflare.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-cloudflare
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/external-dns-cloudflare
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        external-dns:
        {{- toYaml .Values.externalDnsCloudflare | nindent 10 }}
      parameters:
      - name: external-dns.cloudflare.apiToken
        value: {{ .Values.externalDnsCloudflare.apiToken }}
      - name: external-dns.cloudflare.domainFilters
        value: {{ .Values.externalDnsCloudflare.domainFilters }}
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns-cloudflare
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}