{{- if and (.Values.gitlab) (.Values.gitlab.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/gitlab
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: gitlab_operator.global.hosts.domain
          value: {{ .Values.baseDomain }}
        - name: gitlab_operator.global.psql.host
          value: {{ .Values.gitlab.auroraPostgresHost }}
        - name: s3_connect.region
          value: {{ .Values.gitlab.region }}
        - name: s3_connect.aws_access_key_id
          value: {{ .Values.gitlab.awsAccountS3AccessKeyId }}
        - name: s3_connect.aws_secret_access_key
          value: {{ .Values.gitlab.awsAccountS3SecretAccessKey }}
        - name: gitlab_domain
          value: "{{ .Values.gitlabPrefixName }}.{{ .Values.baseDomain }}"
        - name: gitlab-runner.gitlabUrl
          value: "https://{{ .Values.gitlabPrefixName }}.{{ .Values.baseDomain }}"
        - name: gitlab_keycloak_client_secret
          value: {{ .Values.gitlab.gitlabKeycloakConnectorClientSecret }}
        - name: keycloak_domain
          value: {{ .Values.keycloakPrefixName }}.{{ .Values.baseDomain }}
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
