{{- if and (.Values.keycloak) (.Values.keycloak.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/keycloak
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: keycloakx.ingress.rules[0].host
          value: {{ .Values.keycloak.domain }}
        - name: keycloakx.ingress.tls[0].hosts[0]
          value: {{ .Values.keycloak.domain }}
        - name: keycloakx.database.hostname
          value: {{ .Values.keycloak.auroraPostgresHost }}
        - name: adminUser
          value: {{ .Values.adminUser }}
        - name: adminPassword
          value: {{ .Values.adminPassword }}
        - name: argocdClientSecret
          value: {{ .Values.keycloak.argocdClientSecret }}
        - name: keycloakx.extraEnv[0].value
          value: {{ .Values.keycloak.gitlabClientSecret }}
        - name: keycloakx.extraEnv[1].value
          value: {{ .Values.keycloak.harborClientSecret }}
        - name: keycloakx.extraEnv[2].value
          value: {{ .Values.keycloak.grafanaClientSecret }}
        - name: keycloakx.extraEnv[3].value
          value: {{ .Values.keycloak.githubClientSecret }}
        - name: keycloakx.extraEnv[4].value
          value: {{ .Values.keycloak.githubClientId }}
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}