{{- if and (.Values.teleportKubeAgent) (.Values.teleportKubeAgent.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/teleport-kube-agent
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        teleport-kube-agent:
        {{- toYaml .Values.teleportKubeAgent | nindent 10 }}
      parameters:
        - name: teleport-kube-agent.proxyAddr
          value: https://tele.{{ .Values.baseDomain }}:443
        - name: teleport-kube-agent.authToken
          value: {{ .Values.teleportKubeAgent.authToken }}
        - name: teleport-kube-agent.authToken
          value: {{ .Values.teleportKubeAgent.authToken }}
        - name: teleport-kube-agent.authToken
          value: {{ .Values.teleportKubeAgent.authToken }}
        - name: teleport-kube-agent.apps[2].rewrite.headers
          value: |
           - "Host: {{ .Values.grafanaPrefixName }}.{{ .Values.baseDomain }}"
           - "Origin: {{ .Values.grafanaPrefixName }}.{{ .Values.baseDomain }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-cluster
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
