{{- if and (.Values.teleportCluster) (.Values.teleportCluster.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/teleport-cluster
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        teleport-cluster:
        {{- toYaml .Values.teleportCluster | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-cluster
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
