{{- if and (.Values.velero) (.Values.velero.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/velero
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        velero:
        {{- toYaml .Values.velero | nindent 10 }}
      parameters:
        - name: velero.serviceAccount.server.annotations."eks.amazonaws.com/role-arn"
          value: "arn:aws:iam::{{ .Values.velero.serviceAccountName }}:role/eks-velero-backup"
        - name: velero.configuration.backupStorageLocation.bucket
          value: {{ .Values.velero.bucket }}
        - name: velero.configuration.volumeSnapshotLocation.config
          value: {{ .Values.velero.region }}
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
