loki:
  loki:
    storage:
      s3:
        accessKeyId:
        secretAccessKey:
        region:
      bucketNames:
        admin: qke-loki-admin
        ruler: qke-loki-ruler
        chuncks: qke-loki-chunks
    auth_enabled: false
  