apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    version: {{ .Values.gitlab_version }}
    values: {{- .Values.gitlab_operator | toYaml | trim | nindent 5 }}
