apiVersion: v1
kind: Secret
metadata:
  name: gitlab-keycloak-auth
type: Opaque
stringData:
  provider: |
    name: openid_connect
    label: Keycloak
    args:
      name: openid_connect
      scope: 
      - openid 
      - profile
      - email
      - groups
      client_auth_method: query
      discovery: true
      response_type: code
      issuer: https://keycloak.kube.quentrix.com/auth/realms/Quentral
      uid_field: preferred_username
      client_options:
        identifier: gitlab
        secret: tvYSYsZSoTKQ8eTvTZ5j7g3pIHYweRWR
        redirect_uri: https://gitlab.kube-gitlab.quentrix.com/users/auth/openid_connect/callback