apiVersion: v1
kind: Secret
metadata:
  name: gitlab-keycloak-auth
type: Opaque
stringData:
  provider: |
    name: openid_connect
    label: Keycloak
    args:
      name: openid_connect
      scope: 
      - openid 
      - profile
      - email
      - groups
      client_auth_method: query
      discovery: true
      response_type: code
      issuer: https://{{ .Values.keycloak_domain }}/auth/realms/Quentral
      uid_field: preferred_username
      client_options:
        identifier: gitlab
        secret: {{ .Values.keycloak_client_secret }}
        redirect_uri: https://{{ .Values.gitlab_domain }}/users/auth/openid_connect/callback