apiVersion: v1
kind: Secret
metadata:
  name: gitlab-s3
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: {{ .Values.gitlab.region }}
    aws_access_key_id: {{ .Values.gitlab.awsAccountS3AccessKeyId }}
    aws_secret_access_key: {{ .Values.gitlab.awsAccountS3SecretAccessKey }}
