apiVersion: v1
kind: Secret
metadata:
  name: gitlab-s3
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: {{ .Values.s3_connect.region }}
    aws_access_key_id: {{ .Values.s3_connect.awsAccountS3AccessKeyId }}
    aws_secret_access_key: {{ .Values.s3_connect.awsAccountS3SecretAccessKey }}
