apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-creds
  namespace: keycloak
type: Opaque
stringData:
  adminUser: {{ .Values.adminUser }}
  adminPassword: {{ .Values.adminPassword }}
  argocdClientSecret: {{ .Values.argocdClientSecret }}
  gitlabClientSecret: {{ .Values.gitlabClientSecret }}
  harborClientSecret: {{ .Values.harborClientSecret }}
  grafanaClientSecret: {{ .Values.grafanaClientSecret }}
  githubClientSecret: {{ .Values.githubClientSecret }}
  githubClientId: {{ .Values.githubClientId }}