apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-creds
  namespace: keycloak
type: Opaque
data:
  password: {{ .Values.keycloak.adminPassword }}
  username: {{ .Values.keycloak.adminUser }}