teleport-kube-agent:

  # Join token for the cluster. `joinParams` can also pass the join token,
  # but supports more join methods and takes precedence if set.
  authToken: ""

  # Address of the teleport proxy with port (usually :3080).
  proxyAddr: "https://tele.example.com:443"

  # Comma-separated list of roles to enable (any of: kube,db,app)
  roles: "app,node"

  # When set to true, the agent will skip the verification of proxy TLS certificate.
  insecureSkipProxyTLSVerify: true

  # Apps
  apps:
    - name: kubecost
      uri: http://kubecost-cost-analyzer.kubecost.svc.cluster.local:9090
    - name: argocd
      uri: https://argo-cd-argocd-server.argocd.svc.cluster.local
    - name: grafana
      uri: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local
      rewrite:
        headers:
          - "Host: grafana.tele.ops.quentrix.com"
          - "Origin: https://grafana.tele.ops.quentrix.com"