external-dns:
  aws:
    region: "us-east-2"
  serviceAccount:
    create: true
    name: "external-dns-sa"
  sources:
    - ingress
    - service
  provider: cloudflare
  cloudflare:
    apiToken: ""
    proxied: false