external-dns:
  serviceAccount:
    create: false
    name: "external-dns-sa"
## https://github.com/bitnami/charts/blob/main/bitnami/external-dns/values.yaml
## @param sources [array] K8s resources type to be observed for new DNS entries by ExternalDNS
##
  sources:
    - ingress
    # - crd
    # - service
## @param provider DNS provider where the DNS records will be created.
  provider: cloudflare
## Cloudflare configuration to be set via arguments/env. variables
##
  cloudflare:
  ## @param cloudflare.apiToken When using the Cloudflare provider, `CF_API_TOKEN` to set (optional)
  ##
    apiToken: ""
  ## @param cloudflare.proxied When using the Cloudflare provider, enable the proxy feature (DDOS protection, CDN...) (optional)
  ##
    proxied: false

  domainFilters: []
