keycloakx:
  replicas: 1

  # Deploy the latest verion
  image:
    tag: "20.0.1"

  # start: create initial realm from secret which

  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret

  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/realm/"
      readOnly: true

  command:
    - "/opt/keycloak/bin/kc.sh"
    - "--verbose"
    - "start"
    - "--auto-build"
    - "--http-enabled=true"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--hostname-strict-https=false"
    - "--spi-events-listener-jboss-logging-success-level=info"
    - "--spi-events-listener-jboss-logging-error-level=warn"
    - "--import-realm"

  extraEnv: |
    - name: ARGOCD_CLIENT_SECRET
      value: secret
    - name: GITLAB_CLIENT_SECRET
      value: secret
    - name: HARBOR_CLIENT_SECRET
      value: secret
    - name: GRAFANA_CLIENT_SECRET
      value: secret
    - name: GITHUB_CLIENT_SECRET
      value: secret
    - name: GITHUB_CLIENT_ID
      value: client
    - name: KEYCLOAK_IMPORT
      value: /realm/realm.json
    - name: KC_PROXY
      value: "passthrough"
    - name: KEYCLOAK_ADMIN
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: username
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: password
    - name: JAVA_OPTS_APPEND
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=50.0
        -Djava.awt.headless=true
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless


  # This block should be uncommented if you install Keycloak on Kubernetes
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      ingress.kubernetes.io/affinity: cookie
      cert-manager.io/cluster-issuer: letsencrypt-prod
    rules:
      - host: keycloak.example.com
        paths:
          - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
            pathType: Prefix
    tls:
      - hosts:
        - keycloak.example.com
        secretName: keycloak-tls

  resources:
    limits:
      memory: "2048Mi"
    requests:
      cpu: "50m"
      memory: "512Mi"

  # Check database readiness at startup
  dbchecker:
    enabled: true

  database:
    vendor: postgres
    existingSecret: keycloak-pg
    hostname: postgresql
    port: 5432
    username: admin
    database: keycloak-keycloak
