keycloakx:
  # Replicas
  replicas: 1

  # Deploy the latest version
  image:
    tag: "20.0.1"

  # Startup: create initial realm from secret which
  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret

  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/opt/keycloak/data/import/"
      readOnly: true

  # Startup: initial command
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "--verbose"
    - "start"
    - "--auto-build"
    - "--http-enabled=true"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--hostname-strict-https=false"
    - "--spi-events-listener-jboss-logging-success-level=info"
    - "--spi-events-listener-jboss-logging-error-level=warn"
    - "--import-realm"

  # Extra envs
  extraEnv: |
    - name: ARGOCD_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: argocdClientSecret    
    - name: GITLAB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: gitlabClientSecret    
    - name: HARBOR_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: harborClientSecret    
    - name: GRAFANA_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: grafanaClientSecret    
    - name: GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: githubClientSecret    
    - name: GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: githubClientId    
    - name: KC_PROXY
      value: "passthrough"
    - name: KEYCLOAK_ADMIN
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: adminUser
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: adminPassword
    - name: JAVA_OPTS_APPEND
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=50.0
        -Djava.awt.headless=true
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless


  # This block should be uncommented if you install Keycloak on Kubernetes
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      ingress.kubernetes.io/affinity: cookie
      cert-manager.io/cluster-issuer: letsencrypt-staging
    rules:
      - host: keycloak.example.com
        paths:
          - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
            pathType: Prefix
    tls:
      - hosts:
        - keycloak.example.com
        secretName: keycloak-tls

  # Limit resources
  resources:
    limits:
      memory: "2048Mi"
    requests:
      cpu: "50m"
      memory: "512Mi"

  # Check database readiness at startup
  dbchecker:
    enabled: true

  # External Database
  database:
    vendor: postgres
    existingSecret: keycloak-pg
    hostname: postgresql
    port: 5432
    username: admin
    database: keycloak-keycloak

# Secrets
adminUsername: admin
adminPassword: password
argocdClientSecret: secret
gitlabClientSecret: secret
harborClientSecret: secret
grafanaClientSecret: secret
githubClientSecret: secret
githubClientId: client