keycloakx:
  replicas: 1

  # Deploy the latest verion
  image:
    tag: "20.0.1"

  # start: create OpenShift realm which is required by EDP
  extraInitContainers: |
    - name: realm-provider
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          echo '{"realm": "openshift","enabled": true}' > /opt/keycloak/data/import/openshift.json
      volumeMounts:
        - name: realm
          mountPath: /opt/keycloak/data/import

  extraVolumeMounts: |
    - name: realm
      mountPath: /opt/keycloak/data/import

  extraVolumes: |
    - name: realm
      emptyDir: {}

  command:
    - "/opt/keycloak/bin/kc.sh"
    - "--verbose"
    - "start"
    - "--auto-build"
    - "--http-enabled=true"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--hostname-strict-https=false"
    - "--spi-events-listener-jboss-logging-success-level=info"
    - "--spi-events-listener-jboss-logging-error-level=warn"
    - "--import-realm"

  extraEnv: |
    - name: KC_PROXY
      value: "passthrough"
    - name: KEYCLOAK_ADMIN
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: username
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: password
    - name: JAVA_OPTS_APPEND
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=50.0
        -Djava.awt.headless=true
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

  # This block should be uncommented if you install Keycloak on Kubernetes
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      ingress.kubernetes.io/affinity: cookie
      cert-manager.io/cluster-issuer: letsencrypt-staging
    rules:
      - host: keycloak.example.com
        paths:
          - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
            pathType: Prefix
    tls:
      - hosts:
        - keycloak.example.com
        secretName: keycloak-tls

  # This block should be uncommented if you set Keycloak to OpenShift and change the host field
  # route:
  #   enabled: false
  #   # Path for the Route
  #   path: '/'
  #   # Host name for the Route
  #   host: "keycloak.<ROOT_DOMAIN>"
  #   # TLS configuration
  #   tls:
  #     enabled: true

  resources:
    limits:
      memory: "2048Mi"
    requests:
      cpu: "50m"
      memory: "512Mi"

  # Check database readiness at startup
  dbchecker:
    enabled: true

  database:
    vendor: postgres
    existingSecret: keycloak-pg
    hostname: postgresql
    port: 5432
    username: admin
    database: keycloak
