apiVersion: kci.rocks/v1alpha1
kind: DbInstance
metadata:
  name: pg-db-01
spec:
  adminSecretRef:
    Name: {{ .Values.auroraPostgresAdminSecret }}
    Namespace: db-operator
  engine: postgres
  generic:
    host: {{ .Values.auroraPostgresHost }}
    port: {{ .Values.auroraPostgresPort }}