aws-efs-csi-driver:
  controller:
    serviceAccount:
      create: false
  node:
    serviceAccount:
      create: false

  storageClasses:
   - name: efs-sc
     annotations:
       storageclass.kubernetes.io/is-default-class: "false"
     mountOptions:
     - tls
     parameters:
       provisioningMode: efs-ap
       fileSystemId: fs-1122aabb
       directoryPerms: "700"
       basePath: "/sc"
     reclaimPolicy: Delete
     volumeBindingMode: Immediate
   - name: efs-community
     mountOptions:
       - tls
     parameters:
       provisioningMode: efs-ap
       fileSystemId: fs-1122aabb
       directoryPerms: "700"
       basePath: "/community"
     reclaimPolicy: Delete
     volumeBindingMode: Immediate

